"""empty message

Revision ID: 099216b9de97
Revises: 73f10f2e9a26
Create Date: 2025-06-19 10:07:41.194687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099216b9de97'
down_revision = '73f10f2e9a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
